runtime: nodejs20
entrypoint: npm run start

env_variables:
  NEXTAUTH_SECRET: "74b7a3f957cff83bdc2a072ddc883056e331b79919c8c0d795392a0310125737"
  NEXTAUTH_URL: "https://raseed-backend-kmm2mlvmya-uc.a.run.app"
  GOOGLE_CLIENT_ID: "57041492042-rc19uud5npftq070tnjbirqjr783ejfd.apps.googleusercontent.com"
  GOOGLE_CLIENT_SECRET: "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"

instance_class: F1
automatic_scaling:
  max_instances: 5  # Or any number based on your expected load
